[platformio]
default_envs = megaatmega2560

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
  waspinator/AccelStepper@^1.66
  adafruit/Adafruit NeoPixel
  thomasfredericks/Bounce2@^2.71
build_flags =
  -Wall
  -Wextra
