"""Configuration shared by the motor-free Pi 4 radio validation responder."""

I2C_BUS = 1
TRANSCEIVER_I2C_ADDRESS = 0x1A
TRANSCEIVER_DEVICE_ID = 495

PROTOCOL_VERSION = 1
PAIR_ID = 0x44425631

RADIO_GROUP = 73
REMOTE_RADIO_ADDRESS = 1
ROBOT_RADIO_ADDRESS = 2
RADIO_SPEED = 2
RADIO_FREQUENCY = 922
RADIO_TX_POWER = 20

LOOP_SLEEP_SECONDS = 0.002
HEALTH_PERIOD_SECONDS = 2.0
LINK_REPORT_LOST_SECONDS = 1.0

